# Local Profile
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
---
# Dev Profile
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_URL}
      port: 6379
---
